default:

  # Root path for the project source code
  source_path: "E:/Normalization_effects"

  # Data configuration
  data:
    # Paths to raw data for different datasets
    raw_data: 
      breast: "src/data/breast.RData"
      pbmc: "src/data/pbmc.RData"
      liver: "src/data/liver.RData"

    # Paths to normalized data
    normalized: 
      breast: "src/data/normalized/normalized_breast.RData"
      pbmc: "src/data/normalized/normalized_pbmc.RData"
      liver: "src/data/normalized/normalized_liver.RData"

    # Paths to dimensionally reduced data (tSNE and UMAP)
    reduced: 
      breast: 
        tSNE: "src/data/reduced/tSNE_breast.RData"
        UMAP: "src/data/reduced/UMAP_breast.RData"
      pbmc:
        tSNE: "src/data/reduced/tSNE_pbmc.RData"
        UMAP: "src/data/reduced/UMAP_pbmc.RData"
      liver:
        tSNE: "src/data/reduced/tSNE_liver.RData"
        UMAP: "src/data/reduced/UMAP_liver.RData"
        
    # Paths to clustered data (k-means, hierarchical clustering, Louvain, scCAN)
    clustered: 
      breast:
        tSNE:
          kmeans: "src/data/clustered/kmeans_tSNE_breast.RData"
          hclust: "src/data/clustered/hclust_tSNE_breast.RData"
          louvain: "src/data/clustered/louvain_tSNE_breast.RData"
          scCAN: "src/data/clustered/sccan_tSNE_breast.RData"
        UMAP:
          kmeans: "src/data/clustered/kmeans_UMAP_breast.RData"
          hclust: "src/data/clustered/hclust_UMAP_breast.RData"
          louvain: "src/data/clustered/louvain_UMAP_breast.RData"
          scCAN: "src/data/clustered/sccan_UMAP_breast.RData"
          
      pbmc:
        tSNE:
          kmeans: "src/data/clustered/kmeans_tSNE_pbmc.RData"
          hclust: "src/data/clustered/hclust_tSNE_pbmc.RData"
          louvain: "src/data/clustered/louvain_tSNE_pbmc.RData"
          scCAN: "src/data/clustered/sccan_tSNE_pbmc.RData"
        UMAP:
          kmeans: "src/data/clustered/kmeans_UMAP_pbmc.RData"
          hclust: "src/data/clustered/hclust_UMAP_pbmc.RData"
          louvain: "src/data/clustered/louvain_UMAP_pbmc.RData"
          scCAN: "src/data/clustered/sccan_UMAP_pbmc.RData"
          
      liver:
        tSNE:
          kmeans: "src/data/clustered/kmeans_tSNE_liver.RData"
          hclust: "src/data/clustered/hclust_tSNE_liver.RData"
          louvain: "src/data/clustered/louvain_tSNE_liver.RData"
          scCAN: "src/data/clustered/sccan_tSNE_liver.RData"
        UMAP:
          kmeans: "src/data/clustered/kmeans_UMAP_liver.RData"
          hclust: "src/data/clustered/hclust_UMAP_liver.RData"
          louvain: "src/data/clustered/louvain_UMAP_liver.RData"
          scCAN: "src/data/clustered/sccan_UMAP_liver.RData"
  
    # Paths to statistics for processed data
  results:
    reduction:
      pbmc: "src/data/statistics/reduction/pbmc_clustering_results.RData"
      breast: 
        disease: "src/data/statistics/reduction/breast_dis_clustering_results.RData"
        group: "src/data/statistics/reduction/breast_group_clustering_results.RData"
      liver: "src/data/statistics/reduction/liver_clustering_results.RData"
      
    clustering:
      pbmc: "src/data/statistics/clustering/pbmc_clustering_results.RData"
      breast: 
        disease: "src/data/statistics/clustering/breast_dis_clustering_results.RData"
        group: "src/data/statistics/clustering/breast_group_clustering_results.RData"
      liver: "src/data/statistics/clustering/liver_clustering_results.RData"
      
    statistics:
      conover: "src/data/statistics/conover.RData"
        
  
  # Utility script paths
  utils:
    normalization: "src/utils/normalization_utils.R"
    dim_reduction: "src/utils/dim_reduction_utils.R"
    clustering: "src/utils/clustering_utils.R"
    measures: "src/utils/measures.R"
    data_adjustments: "src/utils/data_adjustments.R"
    visualization: "src/utils/visualization.R"
    statistics: "src/utils/statistics.R"

  labels:
    pbmc: 
      CD14+ monocyte: 0
      Dendritic cell: 1
      Cytotoxic T cell: 2
      CD16+ monocyte: 3
      Plasmacytoid dendritic cell: 4
      B cell: 5
      Natural killer cell: 6
      CD4+ T cell: 7
      Megakaryocyte: 8
    breast: 
      disease: 
        Normal tissue: 0
        breast carcinoma: 1
      group: 
        Luminal A: 0
        Normal tissue: 1
        Luminal B: 2
        HER +: 3
        TNBC: 4
    liver: 
      hepatocyte: 0
      macrophage: 1
      T cell: 2
      endothelial cell of hepatic sinusoid: 3
      natural killer cell: 4
      cycling cell: 5
      plasma cell: 6
      B cell: 7
      cholangiocyte: 8
      Kupffer cell: 9
      endothelial cell of vascular tree: 10
      hematopoietic stem cell: 11
      mesothelial cell: 12
